### ISSUE TITLE
reduce style/formatting changes

### ISSUE THREAD

**Issue by dvoytenko** [intuita-inc/codemod-registry#204]
---
:warning::warning: Please do not include any proprietary code in the issue. :warning::warning:

---
Codemod: next/13/replace-next-router

**1. Code before transformation (Input for codemod)**

```
function NewTeamForm({
  createTeamCollapsed,
  flowType,
  formLoading,
  required = true,
  skip,
  isATrial,
  disabled,
  paymentMethodId,
  nameRef,
}) {
 ...
}

```
	
**2. Expected code after transformation (Desired output of codemod)**

Unchanged. Same as old.

**3. Faulty code obtained after running the current version of the codemod (Actual output of codemod)**

```
function NewTeamForm({ 
  createTeamCollapsed, 
  flowType, 
  formLoading, 
  required = true, 
  skip, 
  isATrial, 
  disabled, 
  paymentMethodId, 
  nameRef, 
}) {
  ...
}
```

---	
**Additional context**

**Comment by grzpab** [comment]
@dvoytenko I have two questions:
* does the entire gets transformed by the codemod? (meaning, does it have any statements that manage routing?)
* do you use the "Intuita: Format With Prettier" setting in the VSCode Settings?

**Comment by alex-from-intuita** [comment]
this is only about formatting @dvoytenko ?

**Comment by dvoytenko** [comment]
> this is only about formatting @dvoytenko ?

Yep
