### ISSUE TITLE
[Codemod:next/13/replace-next-router] Object.fromEntries(URLSearchParams) only returns Record<string, string>

### ISSUE THREAD

**Issue by dvoytenko** [intuita-inc/codemod-registry#243]
---
:warning::warning: Please do not include any proprietary code in the issue. :warning::warning:

---
Codemod: next/13/replace-next-router

**1. Code before transformation (Input for codemod)**

```jsx
Object.entries(router.query).forEach(([key, value]) =>
    typeof value === 'string' ? query.set(key, value) : null,
);
```

**2. Expected code after transformation (Desired output of codemod)**

TBD

**3. Faulty code obtained after running the current version of the codemod (Actual output of codemod)**

```jsx
Object.entries(...Object.fromEntries(searchParams ?? new URLSearchParams())).forEach(
    ([key, value]) => typeof value === 'string' ? query.set(key, value) : null
);
```

---	
**Additional context**

1. The resulting code is a valid syntax, but wrong typing on `...Object.fromEntries()`
2. The result of `Object.fromEntries(URLSearchParams)` is `Record<string, string>`, not `Record<string, string | string[]>` as it is with the legacy `Router.query`. Thus the `typeof value === 'string'` would always be `true`.

**Comment by grzpab** [comment]
Fixed by https://github.com/intuita-inc/codemod-registry/pull/293
