### ISSUE TITLE
[Codemod:next/13/replace-next-router] useParams and useSearchParam can be null

### ISSUE THREAD

**Issue by dvoytenko** [intuita-inc/codemod-registry#244]
---
:warning::warning: Please do not include any proprietary code in the issue. :warning::warning:

---
Codemod: next/13/replace-next-router

**1. Code before transformation (Input for codemod)**

```jsx
const parsedParam = getQueryParam(router.query[key]);
```

**2. Expected code after transformation (Desired output of codemod)**

```jsx
const getParam = useCallback((p: string) => params.[p] ?? searchParams?.get(p), [params, searchParams]);
const parsedParam = getQueryParam(getParam(key));
```

**3. Faulty code obtained after running the current version of the codemod (Actual output of codemod)**

```jsx
const getParam = useCallback((p: string) => params[p] ?? searchParams.get(p), [params, searchParams]);
const parsedParam = getQueryParam(getParam(key));
```

---	
**Additional context**

**Comment by grzpab** [comment]
@dvoytenko this has been fixed using the following PR: https://github.com/intuita-inc/codemod-registry/pull/247
