### ISSUE TITLE
[Codemod:next/13/replace-next-router] Jest test mocking next/router

### ISSUE THREAD

**Issue by dvoytenko** [intuita-inc/codemod-registry#246]
---
:warning::warning: Please do not include any proprietary code in the issue. :warning::warning:

---
Codemod: next/13/replace-next-router

**1. Code before transformation (Input for codemod)**

```jsx
import { useRouter } from 'next/router';

jest.mock('next/router', () => ({
  useRouter: jest.fn(() => router),
}));
```

**2. Expected code after transformation (Desired output of codemod)**

```jsx
import { useRouter } from 'next/navigation';

jest.mock('next/navigation', () => ({
  useRouter: jest.fn(() => router),
}));
```

**3. Faulty code obtained after running the current version of the codemod (Actual output of codemod)**

```jsx
import { useRouter } from 'next/navigation';

jest.mock('next/router', () => ({
  useRouter: jest.fn(() => router),
}));
```

---	
**Additional context**

**Comment by grzpab** [comment]
Fixed by https://github.com/intuita-inc/codemod-registry/pull/337
