### ISSUE TITLE
[faulty output] running the cli command `intuita --version` reports 0.0.0

### ISSUE THREAD

**Issue by GeorgeWL** [intuita-inc/codemod-registry#498]
:warning::warning: Please do not include any proprietary code in the issue. :warning::warning:

---

### Faulty codemod

running the cli command `intuita --version` reports 0.0.0

### Code before transformation

not applicable

### Estimated severity

low

### Environment:

-   Intuita CLI version: 0.2.2
-   OS: Windows 10 Enterprise, build 19045.3693
-   Node.js version: 20.10.0

### Additional context

Add any other context about the problem here. This might include the target project, explanation of faulty output related to business logic, relevant links, etc.

installed via `yarn global add intuita` on yarn 1.22.19

Edit: upgraded, still see this

**Comment by grzpab** [comment]
@GeorgeWL hello, we fixed in in the version 0.2.3, just recently published to the NPM. Can you confirm it works for you?

**Comment by mohab-sameh** [comment]
@all-contributors add @GeorgeWL for bug reporting
